import { GoogleGenAI, Type } from "@google/genai";
import { GenerationOutput } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY as string });

export async function generateContent(idea: string, tone: string = "engaging"): Promise<GenerationOutput> {
  const systemInstruction = `You are an expert content creator. Convert the following idea into a high-quality structured output including hook, script, caption, and hashtags. Make it ${tone} and optimized for social media. Return clean JSON only based on the provided schema.`;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: idea,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            hook: { type: Type.STRING, description: "A catchy hook to grab attention." },
            script: { type: Type.STRING, description: "The full video or post script." },
            caption: { type: Type.STRING, description: "An engaging caption for the post." },
            hashtags: { 
              type: Type.ARRAY, 
              items: { type: Type.STRING },
              description: "A list of relevant hashtags."
            }
          },
          required: ["hook", "script", "caption", "hashtags"]
        }
      }
    });

    if (!response.text) {
      throw new Error("No output generated by AI.");
    }

    return JSON.parse(response.text) as GenerationOutput;
  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
}
